performances/benchmark/src/benchmark.cpp, performances/performance_test/examples/json_system_main.cpp, performances/performance_test/src/ros2/tracker.cpp
Adding fixes to some Werrors found while building the commit `cac5b68` on `master` for the performance tool.
=> Fixing some -Werrors

cross-compiling/README.md, cross-compiling/get_ros2_sources.sh, cross-compiling/ignore_pkgs.sh, cross-compiling/ignore_pkgs_scripts/eloquent_ignore.sh, performances/performance_test/include/performance_test/ros2/resource_usage_logger.hpp
musl' malloc.h doesn't support many features as
glib does, mallinfo is one of them.
=> Ignore mallinfo() calls if using musl

performances/benchmark/src/benchmark.cpp, performances/performance_test_factory/include/performance_test_factory/factory.hpp, performances/performance_test_factory/src/factory.cpp
Bugfix for https://github.com/irobot-ros/ros2-performance/issues/11
=> bugfix: do not ignore comand line options for tracker creation (#11)

performances/benchmark/src/benchmark.cpp, performances/performance_test/include/cli/options.hpp, performances/performance_test/include/performance_test/ros2/node.hpp, performances/performance_test/test/test_node.cpp, performances/performance_test_factory/examples/client_nodes_main.cpp, performances/performance_test_factory/examples/publisher_nodes_main.cpp, performances/performance_test_factory/examples/server_nodes_main.cpp, performances/performance_test_factory/examples/simple_client_service_main.cpp, performances/performance_test_factory/examples/simple_pub_sub_main.cpp, performances/performance_test_factory/examples/subscriber_nodes_main.cpp, performances/performance_test_factory/include/performance_test_factory/factory.hpp, performances/performance_test_factory/src/factory.cpp
Now we could run:
`./benchmark topology/sierra_nevada.json --ros_params off`
=> Add ros_params option

.github/CODEOWNERS
=> add @alsora as codeowner

performances/README.md
Update README saying that master branch only works with ROS 2 master
=> add information about different branches

cross-compiling/automatic_cross_compile.sh
Example:
So TARGET=example-1234 -> TARGET_NAME=1234
If no dash present, keep name:
So TARGET=raspbian -> TARGET_NAME=raspbian
=> Use TARGET_NAME as TARGET chars after a dash

cross-compiling/docker_environments/Dockerfile_x86_64
For some reasons these were needed when running the jenkins job
=> Add missing dependencies

performances/benchmark/topology/white_mountain.json, performances/irobot_interfaces_plugin/CMakeLists.txt, performances/irobot_interfaces_plugin/msg/Stamped600kb.msg
Add 600kb msg and set `white_mountain.json` topology to use it on `columbia` topic.
=> Add 600kb msg

cross-compiling/ignore_pkgs_scripts/crystal_ignore.sh, cross-compiling/ignore_pkgs_scripts/dashing_ignore.sh, cross-compiling/ignore_pkgs_scripts/eloquent_ignore.sh, cross-compiling/ignore_pkgs_scripts/foxy_ignore.sh, cross-compiling/ignore_pkgs_scripts/master_ignore.sh, cross-compiling/ignore_pkgs_scripts/x86_64_ignore.sh
see ros repos commit https://github.com/ros2/ros2/commit/69f6a31ffa0b86a6cc169d29b2675c25d96301b2
=> fix ignore pkg script after renaming of kdl library

cross-compiling/automatic_cross_compile.sh, cross-compiling/get_ros2_sources.sh, cross-compiling/get_sysroot.sh, cross-compiling/ignore_pkgs_scripts/foxy_ignore.sh, cross-compiling/ignore_pkgs_scripts/master_ignore.sh
Fixing generic stuff, better error handling in automatic cross compile and added option to use an existing ros workspace
=> update cross-compilation tools

cross-compiling/ignore_pkgs_scripts/x86_64_ignore.sh
after removing them from common one
=> fix missing ignore in arch specific files

cross-compiling/toolchains/x86_64.sh
=> specify CMAKE_SYSTEM_PROCESSOR in x86_64 toolchain

cross-compiling/cc_workspace.sh
see https://unix.stackexchange.com/questions/444946/how-can-we-run-a-command-stored-in-a-variable
=> use array to represent command with whitespaces

cross-compiling/sysroots/Dockerfile_raspbian
=> fix symlink correction in raspbian

performances/performance_test/include/performance_test/ros2/events_logger.hpp, performances/performance_test/include/performance_test/ros2/node.hpp
This PR fixes the counter of a service client as it would not increase its counter when the callback failed.
=> Fix service client counter

performance_test/scripts/plot_scripts/cpu_ram_plot.py, performance_test/scripts/plot_scripts/plot_common.py, performance_test_factory/examples/examples_options.hpp
=> set valid default for executor flag and minor fixes to python scripts

.github/workflows/ci.yml, composition_benchmark/apps/CMakeLists.txt, composition_benchmark/apps/composable_pub_sub_main.cpp, composition_benchmark/apps/multi-producer-node.cpp, performance_test/env.sh, performance_test/include/performance_test/performance_node_base.hpp, performance_test/include/performance_test/performance_node_base_impl.hpp
=> add multi-producer example and minor fixes

performance_test/include/performance_test/performance_node_base.hpp, performance_test/include/performance_test/performance_node_base_impl.hpp, performance_test/include/performance_test/utils/introspection.hpp
=> add type introspection to support messages without data field

performance_metrics/include/performance_metrics/resource_usage_logger.hpp, performance_metrics/src/resource_usage_logger.cpp
=> update rusage logger threads and style

composition_benchmark/src/base_node.cpp, composition_benchmark/src/composable_subscriber.cpp, irobot_benchmark/src/irobot_benchmark.cpp, performance_metrics/include/performance_metrics/stat_logger.hpp, performance_metrics/src/stat_logger.cpp, performance_test/include/performance_test/system.hpp, performance_test/src/system.cpp
=> add argument to log only pub-sub, minor renamings
