irobot-ros/ros2-performance

- cross-compiling/README.md
The script  automatic_cross_compile.sh expects ROS2_DISTRO to be set instead of ROS2_BRANCH
> Fixed a typo in environment variable name

- performances/performance_test/include/performance_test/ros2/node.hpp
Previously the code was performing an integer division.
That frequency value is sent from the publisher to the subscription to compute metrics in a decentralized way.
This resulted in sending a frequency of 0 whenever the period was higher than 1 second, thus resulting in 100% messages being detected as late
> use floating point division to compute frequency correctly

- performances/benchmark/src/benchmark.cpp
- performances/performance_test/include/cli/options.hpp
- performances/performance_test/src/ros2/system.cpp
- performances/performance_test/src/ros2/tracker.cpp
Some updates to facilitate external profiling of this application:
- give names to threads
- add command line option `--tracker off` to disable events logging (e.g. late and too late computation)
> updates for better external profiling

- performances/benchmark/src/benchmark.cpp
- performances/performance_test/include/performance_test/ros2/node.hpp
- performances/performance_test/include/performance_test/ros2/system.hpp
- performances/performance_test/src/ros2/system.cpp
- performances/performance_test/test/test_system.cpp
- performances/performance_test_factory/examples/client_nodes_main.cpp
- performances/performance_test_factory/examples/json_system_main.cpp
- performances/performance_test_factory/examples/publisher_nodes_main.cpp
- performances/performance_test_factory/examples/server_nodes_main.cpp
- performances/performance_test_factory/examples/simple_client_service_main.cpp
- performances/performance_test_factory/examples/simple_pub_sub_main.cpp
- performances/performance_test_factory/examples/subscriber_nodes_main.cpp
- performances/performance_test_factory/include/performance_test_factory/factory.hpp
- performances/performance_test_factory/src/factory.cpp
This PR allows to use a new value in the json topology: `executor_id` specified for each node.
Nodes with the same id will be added to the same executor.
```
{
"node_name": "montreal",
"publishers": [
{"topic_name": "amazon", "msg_type": "stamped9_float32", "period_ms": 10}
],
"executor_id":1
}
```
> add executor_id flag to json to split nodes into different executors

- performances/benchmark/topology/cedar.json
- performances/performance_test/include/performance_test/ros2/node.hpp
- performances/performance_test/src/ros2/system.cpp
- performances/performance_test/test/test_node.cpp
- performances/performance_test_factory/create_new_topology.md
- performances/performance_test_factory/include/performance_test_factory/factory.hpp
- performances/performance_test_factory/src/factory.cpp
- performances/performance_test_plugin_cmake/cmake/generate_script.py
Before this PR, a topology `json` file with period:
`    "period_ms": 15.625` 
was casted to
`    "period_ms": 15`
Now that's fixed. 
Also we have the option to set frequency like: `"freq_hz": 64`
> Fix frequency issue

- performances/performance_test_factory/CMakeLists.txt
- performances/performance_test_factory/include/performance_test_factory/load_plugins.hpp
- performances/performance_test_factory/package.xml
- performances/performance_test_factory/src/factory.cpp
- performances/performance_test_factory/src/load_plugins.cpp
LibPoco has been removed from the ROS dependencies and the functionalities are now part of `rcutils`
https://github.com/ros2/rcutils/issues/216
NOTE: this PR requires master/foxy to work.
> use rcutils instead of libpoco for loading shared libraries

- cross-compiling/cc_workspace.sh
Jenkins can't run Docker in an interactive mode, so this PR adds a flag `--no-it` for the script `cc_workspace.sh` to not use the interactive mode when needed
> Optional interactive docker flag

- cross-compiling/compilation_scripts/cross_compile.sh
- cross-compiling/sysroots/x86_64_get_sysroot.sh
For x86_64 test package builds, its sysroot contains directly the cross-compiled SDK 
`/root/sysroots/<ROS2 install dir>`
This PR is for sourcing `setup.bash` (that only exist when cross-compiling for x86_64)
> Source setup.bash, if exists

- performances/performance_test_factory/src/factory.cpp
In our project we have multiple machines (representing a robot) each on its' own namespace. 
This PR adds a node_namespace attribute for the nodes. I implemented it so if you don't use this parameter nothing changes.
> Extra node option to specify namespace

- performances/benchmark/src/benchmark.cpp
Adding `--ros-args` to the command line options crashes the program. 
Proposed fix: use `rclcpp::remove_ros_arguments` to remove ros specific arguments first.
> fix to allow ros arguments

- performances/performance_test_factory/include/performance_test_factory/load_plugins.hpp
- performances/performance_test_factory/src/load_plugins.cpp
The message type for custom plugin includes the `my_factory_plugin::` prefix which should be removed once the library is loaded in.
> Fix custom message types from plugin package

- cross-compiling/compilation_scripts/cross_compile.sh
C.I relies on the output exit code of this script to identify if the builds have failed. 
Without this commit, the output exit code of `cross_compile.sh` is always succesful even if the colcon build failed, since the addition of the command
`chmod -R a+rwx .`
which is always succesful
> Add exit code to cross_compile.sh

- performances/performance_test/include/performance_test/ros2/node.hpp
Fix: 
`error: converting to 'const std::tuple<std::shared_ptr<void>, performance_test::Tracker, unsigned int>' from initializer list would use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::shared_ptr<rclcpp::Client<irobot_interfaces_plugin::srv::Stamped10b> >&, performance_test::Tracker, int}; <template-parameter-2-2> = void; _Elements = {std::shared_ptr<void>, performance_test::Tracker, unsigned int}]'`
See
https://stackoverflow.com/questions/3413050/initializing-stdtuple-from-initializer-list
https://en.cppreference.com/w/cpp/utility/tuple/tuple
> Fix: Tuples should not be init directly with braced init list

- cross-compiling/compilation_scripts/cross_compile.sh
- performances/performance_test/src/ros2/tracker.cpp
- performances/performance_test_factory/src/factory.cpp
1. Fix compiler warnings
2. After crosscompiling, chmod all dirs but `src` directory. Otherwise it's hard to track custom changes on src directories using git, due all files have changed permissions. Anyway, `src` is already owned by the user so no need to change its permissions.
> Fix compiler warnings

- performances/irobot-benchmark/topology/white_mountain.json
The current default is that all nodes are in the same executor, however we have seen that there are better performances with every node in a separate executor. The default is changed to reflect that.
The system supports json files where the executor is specified only for some nodes. All the other nodes without an explicit executor ID end up in the same executor.
> White Mountain: Use one executor per node

- cross-compiling/cc_workspace.sh
- cross-compiling/compilation_scripts/cross_compile.sh
- cross-compiling/docker_environments/Dockerfile_base
- cross-compiling/docker_environments/Dockerfile_x86_64
- cross-compiling/env.sh
- cross-compiling/toolchains/x86_64.sh
This fixes a problem where during x86_64 build cmake was setting the CMAKE_CROSSCOMPILATION variable to true, due to the presence of toolchain, etc
> split x86_64 and cross-compilation jobs

- performances/irobot-benchmark/src/irobot-benchmark.cpp
- performances/performance_test/include/cli/options.hpp
- performances/performance_test/include/performance_test/ros2/system.hpp
- performances/performance_test/src/ros2/system.cpp
- performances/performance_test/test/test_system.cpp
- performances/performance_test_factory/examples/client_nodes_main.cpp
- performances/performance_test_factory/examples/json_system_main.cpp
- performances/performance_test_factory/examples/publisher_nodes_main.cpp
- performances/performance_test_factory/examples/server_nodes_main.cpp
- performances/performance_test_factory/examples/simple_client_service_main.cpp
- performances/performance_test_factory/examples/simple_pub_sub_main.cpp
- performances/performance_test_factory/examples/subscriber_nodes_main.cpp
```
ROS2 performance benchmark
Usage:
./irobot-benchmark [OPTION...] FILE [FILE...]
-h, --help                    print help
-x, --executor <1/2/3>        the system executor:
1:EventsExecutor.
2:SingleThreadedExecutor.
3:StaticSingleThreadedExecutor (default: 3)
```
Example using EventsExecutor :
```
./irobot-benchmark topology/sierra_nevada.json -x 1
```
Shouldn't be merged until the EventsExecutor PR https://github.com/ros2/rclcpp/pull/1416 gets in.
> Add executor option

- performances/performance_test/include/performance_test/ros2/lifecycle_node.hpp
- performances/performance_test/include/performance_test/ros2/node.hpp
- performances/performance_test/include/performance_test/ros2/system.hpp
- performances/performance_test/include/performance_test/ros2/tracker.hpp
- performances/performance_test/src/ros2/tracker.cpp
- performances/performance_test/test/test_lifecycle_node.cpp
This PR adds separate statistics for publishers.
These monitor the time it takes for the `publisher->publish` function to return.
The current output is something like
```
Publishers stats:
node           topic          size[b]   received[#]    late[#]   too_late[#]    lost[#]   mean[us]  sd[us]    min[us]   max[us]   freq[hz]  duration[s]
prod_a         topic_a        0         0              0         0              0         164       29        154       645       0         5         
prod_b         topic_b        0         0              0         0              0         140       14        119       186       0         5         
```
Most of the fields are empty, but the interesting ones are there
> add publisher stats

- performance_test_factory/package.xml
Due to being used in testing here https://github.com/irobot-ros/ros2-performance/blob/39d3c9aae97e69b6cb68fd75d7905b0d91adaa73/performance_test_factory/CMakeLists.txt#L71
> Explicit dependency on ament_cmake_copyright

- performance_test_plugin_cmake/cmake/generate_factory_plugin.cmake
- Galactic support is still required in certain cases and this PR adds back in that tiny bit of support
- Leverage the cmake `if(COMMAND ...)` to check which macro is available thus not relying on the environment (`ROS_DISTRO`, etc)
- Launch the [OSRF-Humble docker container](https://docs.ros.org/en/humble/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.html#run-two-nodes-in-a-single-docker-container), clean build and run this package
- Launch the [OSRF-Galactic docker container](https://docs.ros.org/en/galactic/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.html#run-two-nodes-in-a-single-docker-container), clean build and run this package
```bash
root@<some-machine>:~/ros/performance_ws# colcon build
Starting >>> performance_test_msgs
Finished <<< …
```
> Add to the generate_factory_plugin cmake back-support for galactic

- performance_test/include/performance_test/performance_node_base_impl.hpp
Since we care about the perfomances of ROS2, we should try not add unnecessary overhead to profile just ROS2 methods performances.
This will also be useful when comparing with loaned messages, since it doesn't initalize memory by default.
> Don't initalize messages

- performance_test_factory/src/cli_options.cpp
Disable event-tracking by default.
Tested:
- `osrf/ros:humble-desktop` docker image
- with the change, ran: 
```
$ ./irobot_benchmark/irobot_benchmark \
--topology src/ros2-performance/irobot_benchmark/topology/white_mountain.json
```
Result: no events text file present
```
root@AMER-H62V3J3:~/ros/performance_ws# ll white_mountain_log/
total 28
drwxr-xr-x 2 root      root      4096 Aug 25 14:37 ./
drwxrwxr-x 8 612582126 612582126 4096 Aug 25 14:37 ../
-rw-r--r-- 1 root      root      9403 Aug 25 14:37 latency_all.txt
-rw-r--r-- 1 root      root       192 Aug 25 14:37 latency_total.txt
-rw-r--r-- 1 root      root      1313 Aug 25 14:37 resources.txt
```
> Turn off event-tracking by default

- irobot_benchmark/README.md
- irobot_benchmark/src/irobot_benchmark.cpp
- performance_metrics/include/performance_metrics/events_logger.hpp
- performance_metrics/include/performance_metrics/resource_usage_logger.hpp
- performance_metrics/include/performance_metrics/stat_logger.hpp
- performance_metrics/include/performance_metrics/tracker.hpp
- performance_metrics/src/events_logger.cpp
- performance_metrics/src/resource_usage_logger.cpp
- performance_metrics/src/stat_logger.cpp
- performance_metrics/src/tracker.cpp
- performance_test/include/performance_test/system.hpp
- performance_test/src/system.cpp
- performance_test_factory/include/performance_test_factory/cli_options.hpp
- performance_test_factory/src/cli_options.cpp
- this impacts the 3 data output loggers
- csv output is enabled via a `--csv-out on/off` flag to the main `irobot_benchmark` executable (no flag for the other executables and experimental applications, so they'll default to the previous output type)
- The default (no `--csv-out` flag, or `--csv-out off`) remains the same: space-delimited output
- This commit also introduces a `metadata.txt` file, currently containing the runtime options but is intended to include other pertinent meta information.
- `osrf/ros:humble-desktop` docker container
- a docker container `FROM osrf/ros2:devel` to test against `rolling` and here the `master` branch of `ros2-performance`
**events.txt**
```
Time[ms],Caller,Code,Description
0,SYSTEM,0,[discovery] PDP completed
0,SYSTEM,0,[discovery] EDP completed
``` …
> Add changes to support full comma-delimited output

- performance_metrics/src/resource_usage_logger.cpp
- performance_test_factory/src/cli_options.cpp
Previously, resource-utilization (RU) was calculated as an average since program-start.  This PR changes the calculation to average over the last `period` milliseconds, where `period` is the sampling flag, e.g. `---sampling 1000`.
This change brings RU more inline with programs like `htop` and is the idea, and request, of @mauropasse 
- Note the question below.  Should this change be a flag exposed by `irobot_benchmark`?  E.g. exposing the ability to choose the desired behavior?
- Also note the change to the _default_ resource sampling period.  That isn't necessarily required.
Tests were conducted within a `rolling` docker container
- `white-mountain` topology on x86
- 60sec test duration
- sampling period of 1000ms
- note for example the percent-CPU-utilization differences:
**this …
> Update the resource-utilization calc: average over the last N ms

- performance_metrics/src/events_logger.cpp
- performance_metrics/src/resource_usage_logger.cpp
- performance_metrics/src/stat_logger.cpp
Our internal query engine cannot handle symbols in the keys (without escaping them) of the headers of the results files. This PR replaces symbols like % with perc etc.
**Before**
```
time[ms]   cpu[%]  arena[KB]       in_use[KB]      mmap[KB]        rss[KB]         vsz[KB]         
0          0       0             0                    0              0              0              
1000           1.9       41844          36078          129292         97260          3396848        
...
```
**After**
```
time_ms        cpu_perc  arena_KB       in_use_KB      mmap_KB        rss_KB         vsz_KB         
0              0         0              0              0              0              0              
1000           1.9       41844          36078          129292         97260 …
```
> Remove symbols like '[' and '#' from the headers of the results files
